name: numeral
description: >-
  A Dart library for Format number into beautiful string,
  Format the number into a beautiful, readable and short string.

version: 2.0.1
homepage: https://github.com/medz/numeral.dart
repository: https://github.com/medz/numeral.dart
issue_tracker: https://github.com/medz/numeral.dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: any
