name: numeral
description: >-
  A Dart library for Format number into beautiful string,
  Format the number into a beautiful, readable and short string.

version: 3.1.1
repository: https://github.com/medz/numeral.dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.25.15
  lints: ^5.0.0
